services:
  web:
    build: .
    init: true
    working_dir: /app
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "4000:4000"
      - "35729:35729"

volumes:
  bundle_cache:
